# poloniex configuration
poloniex:
  api:
    wsApi: wss://api.poloniex.com
    wsApi2: wss://api2.poloniex.com/
    tradeHistoryUrl: https://poloniex.com/public?command=returnTradeHistory&currencyPair={currencyPair}&start={startTime}&end={endTime}
    tradingApi: https://poloniex.com/tradingApi
  tradeConfig:
    realPrice: true
    # Minimal order amount
    minBtcTradeAmount: 0.000105
    # 5$ approximately
    realBtcTradeAmount: 0.01

# Spring app configuration
server:
  port: 8090