# poloniex configuration
poloniex:
  api:
    wsApi: wss://api.poloniex.com
    wsApi2: wss://api2.poloniex.com/
    tradeHistoryUrl: https://poloniex.com/public?command=returnTradeHistory&currencyPair={currencyPair}&start={startTime}&end={endTime}
    tradingApi: https://poloniex.com/tradingApi
  trade:
    realPrice: true

# Spring app configuration
server:
  port: 8090