server:
  port: 8089

poloniex:
  apiResources:
    wsUrl: wss://api.poloniex.com
    tradeHistoryUrl: https://poloniex.com/public?command=returnTradeHistory&currencyPair={currencyPair}&start={startTime}&end={endTime}