server:
  port: 8089

poloniex:
  apiResources:
    wsApi: wss://api.poloniex.com
    wsApi2: wss://api2.poloniex.com
    tradeHistoryResource: https://poloniex.com/public?command=returnTradeHistory&currencyPair={currencyPair}&start={startTime}&end={endTime}